#!/usr/bin/with-contenv bash

echo "Checking for valid arch options"
case $ARCH_VAR in
  x86-64)
    echo "Proceeding with x86-64 arch"
    ;;
  aarch64)
    echo "Proceeding with aarch64 arch"
    ;;
  arm)
    echo "Proceeding with arm arch"
    ;;
  *)
    echo "Unrecognized or invalid arch selection, canceling install"
    exit 1
    ;;
esac

# Grab latest versions of the app
/bin/wget -O /bin/airupnp-x86-64-static http://pic.sunmite.com/AirConnect/airupnp-x86-64-static
/bin/chmod +x /bin/airupnp-x86-64-static
